version: '3.8'

services:
  rac-panel:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - /opt/1cv8:/opt/1cv8:ro
    environment:
      - ALLOW_USER_PASSWORD_CHANGE=false
      - FLASK_ENV=production
      - DATA_DIR=/app/data
      - CLUSTER_USER=your_cluster_user
      - CLUSTER_PWD=your_cluster_password
      - RAC_PATH=/opt/1cv8/x86_64/current/rac
      - FLASK_PORT=5000
      - FLASK_SECRET_KEY=your_secret_key  # Change this in production
    restart: unless-stopped
